# Generated by Django 5.0.6 on 2024-05-28 08:29

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEmployee',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(default='+996', max_length=14)),
                ('experience', models.CharField(default=2, max_length=30, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(30)])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('category', models.CharField(default='category is not Detected', max_length=100)),
                ('description', models.TextField(verbose_name='Write the small description of your experience')),
                ('recommendation', models.CharField(blank=True, max_length=100, verbose_name='Which companies did you worked in the past and describe the reasons why did you prefer our company')),
                ('job', models.CharField(max_length=50, verbose_name='What position are you applying for?')),
                ('salary', models.PositiveIntegerField(default=2500, verbose_name='how much money do you want per month for your work?')),
                ('preferences', models.CharField(default='Yes', max_length=100, verbose_name='Did you feel comfortable to work with the colleague from other countries and genders?')),
                ('duration', models.PositiveIntegerField(default=10, verbose_name='How long are you going to work in our company?')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
