# Generated by Django 5.0.6 on 2024-05-28 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customemployee',
            name='age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(99)]),
        ),
        migrations.AlterField(
            model_name='customemployee',
            name='experience',
            field=models.PositiveIntegerField(default=2, max_length=30, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
