# Generated by Django 5.0.6 on 2024-05-15 08:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category_book',
            field=models.CharField(choices=[('Romantic', 'Romantic'), ('Drama', 'Drama'), ('Comedy', 'Comedy'), ('Fantasy', 'Fantasy'), ('Old Literature', 'Old Literature'), ('Autobiography', 'Autobiography')], max_length=100, verbose_name='What is the category of the book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='opinion_book',
            field=models.CharField(blank=True, max_length=100, verbose_name='Write your opinion about this book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Write the name of the book'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_book', to='book.book')),
            ],
        ),
    ]
