# Generated by Django 5.0.6 on 2024-05-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_category_book_alter_book_opinion_book_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='starts',
            new_name='stars',
        ),
    ]
