# Generated by Django 5.0.6 on 2024-05-15 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_rename_starts_review_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='text',
        ),
    ]
